added some new boards and universal header + blink samples
platformio/platform-intel_mcs51 pull request #41
Opened 2021-06-10 03:35 UTC by snovotill

I have no idea how to use github but nevertheless here are some new board definitions (including Nuvoton) and examples which include the new MCU header files. The original 805x headers have also been made more universal by ensuring they contain pin definitions in both accepted formats, that being PXY as well as PX_Y. Extra Flags are added to the previously existing STC headers so that boards can be automatically detected at compile time as is demonstrated within anymcu-blink main.c

2021-07-16 04:19 UTC, snovotill commented
Requesting some comments from the community. I'm currently working on BSP files (MCU header files) which need to be included for the STC and Nuvoton. I'll upload those soon.

2022-01-06 16:47 UTC, LovelyA72 commented
This is truly awesome! finally, we have nuvoton support in platformio. I don't know why still nobody is reviewing this pull request.

2022-04-09 02:26 UTC, cocus commented
I've tried to use the 90C516RD+ but it's similar to the 89C516RD+ by the looks of it. This PR would've solved my issue beforehand... Not sure why it's not merged yet

2022-04-10 18:04 UTC, ivankravets requested changes
Thanks for the PR! Please resolve my comments above and we would be glad to merge this PR.

2022-04-10 18:04 UTC, ivankravets commented on boards/at89s51.json
> +{
Please RENAME all JSON files to the original TARGET NAMEs. Typically, make them UPPER CASE. We keep target devices in sync with vendor naming.

`boards/at89s51.json` -> `boards/AT89S51.json`

2022-04-10 18:04 UTC, ivankravets commented on boards/eol.sh
> +#!/bin/bash
Remove this file

2022-04-10 18:04 UTC, ivankravets commented on examples/anymcu-blink/platformio.ini
> +; PlatformIO Project Configuration File
Please add new examples to the CI list
https://github.com/platformio/platform-intel_mcs51/blob/develop/.github/workflows/examples.yml#L12

2022-04-10 18:04 UTC, ivankravets commented on examples/anymcu-blink/platformio.ini
> +[env:n76e003]
It looks like this example supports multiple boards (target devices). Does it make sense to declare multiple configuration environments to test them?

2022-04-10 18:04 UTC, ivankravets commented on examples/anymcu-blink/src/workspace.code-workspace
> +{
Please remove redundant files.

2022-04-11 09:35 UTC, merged

2022-04-11 09:37 UTC, ivankravets commented
I fixed all issues, thanks for the PR! Anyone in this thread, please re-test this PR using the next guide:

1. Upgrade PIO Core to the latest dev version `pio upgrade --dev`
2. Use the GIT version of dev-platform in `platformio.ini` => `platform = https://github.com/platformio/platform-intel_mcs51.git`
3. Open the system terminal, change the working directory to the project folder, and type `pio pkg update`
4. Build project
5. Upload firmware.

Does it work now?

P.S: Please note that all board manifests were renamed to upper case.

2022-04-29 21:26 UTC, cocus commented
Tested with a 90C516RD+, works as expected.